### ISSUE TITLE
自动刷取”黄昏的音序“会导致处理器频率严重异常

### ISSUE THREAD

**Issue by QingWanNiang** [MAA1999/M9A#208]
硬件信息：精粤Z790M+12700KF
电源计划已经设置为高性能
在刷取肉鸽的时候，会出现处理器频率严重降低的异常，并且伴随严重的画面和声音卡顿，M9A运行结束故障现象消失
附件图片：
1.处理器平台基本信息，已经配置足够高的功耗墙，可见右下角摘要频率正常（50-38）
![0](https://github.com/user-attachments/assets/31f78f44-7f0e-4be6-b085-d59daf65c9af)
2.故障复现时的频率和电压：
![1](https://github.com/user-attachments/assets/f56855a4-9db5-4c55-b097-5d657904005d)
3.故障复现时候的温度和功耗，可见完全处于限制之内，理应不会撞墙
![2](https://github.com/user-attachments/assets/6d57fdcc-48bc-43ce-9867-24a07c976e68)
4.HWINFO64给出的频率受限原因，但是经过排查BIOS这些限制都不存在，建议仅参考一下
具体的BIOS设置：IA&GT Core IccMaxLimit=Unlimited（2048A）
Intel TVB Support=Disabled
PL1=PL2=300W
AVX Ratio Offset=0
![3](https://github.com/user-attachments/assets/8ddce11c-e0c1-44e1-859b-6a2b3f7b1322)
相关问题我也反馈给了精粤的工程师，希望他们能同步排查一下主板问题，目前不清楚是软件本身BUG还是主板BIOS BUG于是两百年都反馈下

**Comment by MistEO** [comment]
有兴趣可以试试新版本 maafw 的 GPU 加速 https://github.com/MaaXYZ/MaaFramework/releases
