### ISSUE TITLE
常规作战进不去，在入口反复横跳

### ISSUE THREAD

**Issue by gsxgmpkt9020** [MAA1999/M9A#288]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

常规作战进不去，在入口反复横跳

### Version

2.5.6

### 日志和配置文件

[maa.log](https://github.com/user-attachments/files/18221190/maa.log)
[config.json](https://github.com/user-attachments/files/18221192/config.json)

### 配置信息

WIN 10 22H2

MUMU 12

模拟器分辨率:1280 X 720

 MuMu 12没看见有截图增强开关

 GPU 加速： AMD X5700XT

**Comment by Windsland52** [comment]
没进入“洞穴的囚徒”这个章节是吧

**Comment by Windsland52** [comment]
感觉是滑太快了，滑过头了

**Comment by Windsland52** [comment]
一会儿我改一下

**Comment by Windsland52** [comment]
试着替换resource/base/pipeline下的combat.json
[combat.json](https://github.com/user-attachments/files/18221520/combat.json)
